env: "dev"

http_server:
  address: "0.0.0.0"
  port: 8080
  timeout: 60
  idle_timeout: 120

services:
  user:
    address: "user-service"
    port: 50051
  auth:
    address: "auth-service"
    port: 50052
  post:
    address: "post-service"
    port: 50053
  relation:
    address: "relation-service"
    port: 50054
  notification:
    address: "notification-service"
    port: 50055

jwt:
  secret: "my-secret"
  access_expires_at: "1m"
  refresh_expires_at: "5m"

prometheus:
  address: "0.0.0.0"
  port: 9106
